version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - logging-service

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    depends_on:
      - mongo
      - logging-service

  logging-service:
    build: ./logging-service
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
